Tableaux Numpy

In [1]:
import numpy as np


In [2]:
my_list=[1,3,5]
nparray= np.array(my_list)

In [3]:
matrix =[[1,2,3],[4,5,6],[4,3,8]]
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [4, 3, 8]])

In [4]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [5]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [6]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.linspace(2,15,16)

array([ 2.        ,  2.86666667,  3.73333333,  4.6       ,  5.46666667,
        6.33333333,  7.2       ,  8.06666667,  8.93333333,  9.8       ,
       10.66666667, 11.53333333, 12.4       , 13.26666667, 14.13333333,
       15.        ])

In [9]:
# matrice identite
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [10]:
help(np.eye)

Help on function eye in module numpy:

eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)
    Return a 2-D array with ones on the diagonal and zeros elsewhere.
    
    Parameters
    ----------
    N : int
      Number of rows in the output.
    M : int, optional
      Number of columns in the output. If None, defaults to `N`.
    k : int, optional
      Index of the diagonal: 0 (the default) refers to the main diagonal,
      a positive value refers to an upper diagonal, and a negative value
      to a lower diagonal.
    dtype : data-type, optional
      Data-type of the returned array.
    order : {'C', 'F'}, optional
        Whether the output should be stored in row-major (C-style) or
        column-major (Fortran-style) order in memory.
    
        .. versionadded:: 1.14.0
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__ar

In [11]:
np.random.rand(6,4)

array([[0.98819844, 0.884947  , 0.27547954, 0.5499942 ],
       [0.18783065, 0.39693071, 0.67678023, 0.78724998],
       [0.90836456, 0.35235898, 0.38989422, 0.25098184],
       [0.32741892, 0.9346316 , 0.85166937, 0.18143807],
       [0.41894739, 0.85157432, 0.53252456, 0.45244185],
       [0.31376499, 0.26685558, 0.79621136, 0.24136561]])

In [12]:
np.random.randn(10)

array([ 2.22476884, -1.73196092,  0.21312845,  2.27900669,  0.62274385,
        1.4867547 , -0.43603057, -0.73518016,  1.87439666, -0.30561811])

In [13]:
np.random.randint(4,10,(2,6))

array([[8, 8, 6, 9, 8, 5],
       [7, 7, 4, 8, 5, 4]])

In [14]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [15]:
arr = np.arange(0,25)

In [16]:
arr.reshape(5,5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
x= np.random.randint(0,101,10)

In [24]:
x

array([ 14,  61,  61,  46,  61,  50,  54,  63,   2, 100])

In [22]:
x.argmax()

9

In [23]:
x.max()

100

In [25]:
x.reshape(2,5)

array([[ 14,  61,  61,  46,  61],
       [ 50,  54,  63,   2, 100]])

In [26]:
x.shape

(10,)

In [28]:
x.reshape(2,5).shape

(2, 5)